<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonSemuaKategori</name>
   <tag></tag>
   <elementGuidId>3c0b182f-7a1f-4ac6-85f8-cd7d8b5787bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[contains(.,'Semua')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[contains(.,'Semua')]</value>
      <webElementGuid>4aa64c58-2a41-4005-924b-5aea3b9cce09</webElementGuid>
   </webElementProperties>
</WebElementEntity>
