<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonKategoriElektronik</name>
   <tag></tag>
   <elementGuidId>156f4c96-fd5d-4bb2-aae6-eb5913ec1343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[5]</value>
      <webElementGuid>217e6c26-f78e-478d-b2a3-0bfc497f0fba</webElementGuid>
   </webElementProperties>
</WebElementEntity>
