<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonKategoriBaju</name>
   <tag></tag>
   <elementGuidId>c11624a0-9da9-47fe-b5ca-3e4b16691cb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//a[4]</value>
      <webElementGuid>cfe4cac7-0b67-4ecc-a0d2-3e3467b4f169</webElementGuid>
   </webElementProperties>
</WebElementEntity>
