<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtfieldCity</name>
   <tag></tag>
   <elementGuidId>31d2251d-5941-4c34-b4f7-46fabb3c6aa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='user_city_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='user_city_id']</value>
      <webElementGuid>63b0a9df-35a9-4263-aae2-c4f007a5bf57</webElementGuid>
   </webElementProperties>
</WebElementEntity>
